name: heatsentinel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0
  geocoding: ^2.1.0

  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0
  firebase_messaging: ^14.4.0
  flutter_compass: ^0.8.0
  wifi_iot: ^0.3.19


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_bg.png
